version: '2'
services:
    db:
        image: mysql:5.6
        container_name: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        image: php:7.1-apache
        container_name: php
        ports:
            - 8000:80
        volumes:
            - ./www:/var/www/html/
